Rename bkctl to bkctld

diff --git a/bkctld b/bkctld
--- a/bkctld
+++ b/bkctld
@@ -1,11 +1,11 @@
 #!/bin/bash
 #
-# bkctl is a shell script to create and manage a backup server which will
+# bkctld is a shell script to create and manage a backup server which will
 # handle the backup of many servers (clients).
 
 id=$(id -u)
 if [ $id != 0 ]; then
-    echo "Error, you need to be root to run bkctl !" >&2
+    echo "Error, you need to be root to run bkctld !" >&2
     exit 1
 fi
 
@@ -17,7 +17,7 @@ else
 fi
 
 sub_help(){
-    echo "Usage: bkctl <subcommand> [options]"
+    echo "Usage: $0 <subcommand> [options]"
     echo "Subcommands:"
     echo "	init		<jailname>					Init jail <jailname>"
     echo "	update		(<jailname>|all)				Update jail <jailname> or all"
@@ -92,8 +92,8 @@ sub_start() {
 		echo "Jail $jail already running !" >&2
 		exit 1
 	fi
-	mount -t proc bkctl-proc-${jail} ${JAILDIR}/${jail}/proc/
-	mount -nt tmpfs bkctl-dev-${jail} ${JAILDIR}/${jail}/dev
+	mount -t proc bkctld-proc-${jail} ${JAILDIR}/${jail}/proc/
+	mount -nt tmpfs bkctld-dev-${jail} ${JAILDIR}/${jail}/dev
 	mknod -m 622 ${JAILDIR}/${jail}/dev/console c 5 1
 	mknod -m 666 ${JAILDIR}/${jail}/dev/null c 1 3
 	mknod -m 666 ${JAILDIR}/${jail}/dev/zero c 1 5
@@ -167,13 +167,13 @@ sub_sync() {
 	port=$(get_port $jail)
 	key=$(get_key $jail)
 	rsync -a ${CONFDIR}/$jail $NODE:${CONFDIR}/$jail
-	bkctl key $jail > /tmp/evobackup-${jail}.pub
+	bkctld key $jail > /tmp/evobackup-${jail}.pub
 	rsync -a /tmp/evobackup-${jail}.pub $NODE:/tmp/evobackup-${jail}.pub
-	ssh $NODE bkctl init $jail
-	ssh $NODE bkctl port $jail $port
-	ssh $NODE bkctl key $jail /tmp/evobackup-${jail}.pub
+	ssh $NODE bkctld init $jail
+	ssh $NODE bkctld port $jail $port
+	ssh $NODE bkctld key $jail /tmp/evobackup-${jail}.pub
 	for ip in $(get_ip $jail); do
-		ssh $NODE bkctl ip $jail $ip
+		ssh $NODE bkctld ip $jail $ip
 	done
 }
 
