Comment of ElasticSearch dump. No need to be activated by default...

diff --git a/zzz_evobackup b/zzz_evobackup
--- a/zzz_evobackup
+++ b/zzz_evobackup
@@ -97,19 +97,19 @@ mkdir -p -m 700 /home/backup
 # Dump Redis
 # cp /var/lib/redis/dump.rdb /home/backup/
 
-# Dump ElasticSearch
-# Disable ES translog flush
-curl -s -XPUT 'localhost:9200/_settings' -d '{"index.translog.disable_flush": true}' >/dev/null
-# Flushes translog
-curl -s 'localhost:9200/_flush' | grep -qe '"ok":true'
-# If it succeed, do an rsync of the datadir
-if [ $? -eq 0 ]; then
-    rsync -a /var/lib/elasticsearch /home/backup/
-else
-    echo "Error when flushing ES translog indexes."
-fi
-# In any case re-enable translog flush
-curl -s -XPUT 'localhost:9200/_settings' -d '{"index.translog.disable_flush": false}' > /dev/null
+## Dump ElasticSearch
+## Disable ES translog flush
+#curl -s -XPUT 'localhost:9200/_settings' -d '{"index.translog.disable_flush": true}' >/dev/null
+## Flushes translog
+#curl -s 'localhost:9200/_flush' | grep -qe '"ok":true'
+## If it succeed, do an rsync of the datadir
+#if [ $? -eq 0 ]; then
+#    rsync -a /var/lib/elasticsearch /home/backup/
+#else
+#    echo "Error when flushing ES translog indexes."
+#fi
+## In any case re-enable translog flush
+#curl -s -XPUT 'localhost:9200/_settings' -d '{"index.translog.disable_flush": false}' > /dev/null
 
 # Dump MBR / table partitions
 # dd if=/dev/sda of=/home/backup/MBR bs=512 count=1 2>&1 | egrep -v "(records in|records out|512 bytes)"
