bkctld-key: check if the key file is readable

diff --git a/lib/bkctld-key b/lib/bkctld-key
--- a/lib/bkctld-key
+++ b/lib/bkctld-key
@@ -22,8 +22,8 @@ if [ -z "${keyfile}" ]; then
         cat "${jail_path}/${AUTHORIZED_KEYS}"
     fi
 else
-    [ -e "${keyfile}" ] || error "Keyfile ${keyfile} dosen't exist !"
+    test -r "${keyfile}" || error "${jail_name}: SSH key '${keyfile}' is missing or is not readable."
     cat "${keyfile}" > "${jail_path}/${AUTHORIZED_KEYS}"
     chmod 600 "${jail_path}/${AUTHORIZED_KEYS}"
-    notice "${jail_name}: update key => ${keyfile}"
+    notice "${jail_name}: SSH key has been updated with ${keyfile}"
 fi
