bkctld-remove: confirmation before removal of jails if not in force mode

diff --git a/lib/bkctld-remove b/lib/bkctld-remove
--- a/lib/bkctld-remove
+++ b/lib/bkctld-remove
@@ -2,6 +2,8 @@
 #
 # Description: Remove jail and all dated copies (incs)
 # Usage: remove <jailname>|all
+# Return codes:
+# * 101 : jail removal aborted
 #
 
 # shellcheck source=./includes
@@ -15,6 +17,28 @@ jail_path=$(jail_path "${jail_name}")
 incs_path=$(incs_path "${jail_name}")
 
 test -d "${jail_path}" || error "${jail_name}: jail not found" 2
+
+if [ "${FORCE}" != "1" ]; then
+    answer=""
+    while :; do
+        printf "> Are you sure you want to delete jail \`%s'? [Y,n,?] " "${jail_name}"
+        read -r answer
+        case $answer in
+            [Yy]|"" )
+                break
+                ;;
+            [Nn] )
+                tty -s && echo "Abort." >&2
+                exit 101
+                ;;
+            * )
+                printf "y - yes, execute actions and exit\n"
+                printf "n - no, don't execute actions and exit\n"
+                printf "? - print this help\n"
+                ;;
+        esac
+    done
+fi
 
 "${LIBDIR}/bkctld-is-on" "${jail_name}" && "${LIBDIR}/bkctld-stop" "${jail_name}"
 
