rewrite log messages and format

diff --git a/lib/bkctld-ip b/lib/bkctld-ip
--- a/lib/bkctld-ip
+++ b/lib/bkctld-ip
@@ -15,7 +15,7 @@ if [ ! -n "${jail_name}" ]; then
 fi
 jail_path=$(jail_path "${jail_name}")
 
-test -d "${jail_path}" || error "${jail_name}: jail is missing."
+test -d "${jail_path}" || error "${jail_name}: jail not found"
 
 jail_sshd_config="${jail_path}/${SSHD_CONFIG}"
 
@@ -40,9 +40,9 @@ else
     if grep -q -E "^AllowUsers" "${jail_sshd_config}"; then
         sed -i "s~^AllowUsers .*~${allow_users}~" "${jail_sshd_config}"
     else
-        error "${jail_name}: No \`AllowUsers' directive found in \`${jail_sshd_config}'"
+        error "No \`AllowUsers' directive found in \`${jail_sshd_config}'"
     fi
-    notice "${jail_name}: IP whitelist updated with \`${ip}'"
+    notice "Update IP whitelist with \`${ip}' for jail \`${jail_name}' : OK"
     "${LIBDIR}/bkctld-reload" "${jail_name}"
     "${LIBDIR}/bkctld-firewall" "${jail_name}"
 fi
diff --git a/lib/bkctld-key b/lib/bkctld-key
--- a/lib/bkctld-key
+++ b/lib/bkctld-key
@@ -15,15 +15,15 @@ if [ ! -n "${jail_name}" ]; then
 fi
 jail_path=$(jail_path "${jail_name}")
 
-test -d "${jail_path}" || error "${jail_name}: jail is missing."
+test -d "${jail_path}" || error "${jail_name}: jail not found"
 
 if [ -z "${keyfile}" ]; then
     if [ -f "${jail_path}/${AUTHORIZED_KEYS}" ]; then
         cat "${jail_path}/${AUTHORIZED_KEYS}"
     fi
 else
-    test -r "${keyfile}" || error "${jail_name}: SSH key \`${keyfile}' is missing or is not readable."
+    test -r "${keyfile}" || error "SSH key \`${keyfile}' for jail \`${jail_name}' is missing or is not readable."
     cat "${keyfile}" > "${jail_path}/${AUTHORIZED_KEYS}"
     chmod 600 "${jail_path}/${AUTHORIZED_KEYS}"
-    notice "${jail_name}: SSH key has been updated with \`${keyfile}'"
+    notice "Update SSH key \`${keyfile}' for jail \`${jail_name}' : OK"
 fi
diff --git a/lib/bkctld-start b/lib/bkctld-start
--- a/lib/bkctld-start
+++ b/lib/bkctld-start
@@ -13,7 +13,7 @@ if [ -z "${jail_name}" ]; then
 fi
 jail_path=$(jail_path "${jail_name}")
 
-test -d "${jail_path}" || error "${jail_name}: jail is missing."
+test -d "${jail_path}" || error "${jail_name}: jail not found"
 
 "${LIBDIR}/bkctld-is-on" "${jail_name}" && exit 0
 
@@ -21,7 +21,7 @@ test -d "${jail_path}" || error "${jail_name}: jail is missing."
 mount_jail_fs "${jail_name}"
 
 # Start SSH in the chroot
-chroot "${jail_path}" /usr/sbin/sshd -E /var/log/authlog || error "${jail_name}: failed to start SSH."
+chroot "${jail_path}" /usr/sbin/sshd -E /var/log/authlog || error "Failed to start SSH for jail \`${jail_name}'"
 pidfile="${jail_path}/${SSHD_PID}"
 
 # Wait for SSH to be up
@@ -37,7 +37,7 @@ for try in $(seq 1 10); do
 done
 
 if [ -n "${pid}" ]; then
-    notice "${jail_name}: jail has been started [${pid}]"
+    notice "Start jail \`${jail_name}' : PID \`${pid}'"
 else
-    error "${jail_name}: failed to fetch SSH pid within 3 sec."
+    error "Failed to fetch SSH PID for jail \`${jail_name}' within 3 seconds"
 fi
diff --git a/lib/bkctld-update b/lib/bkctld-update
--- a/lib/bkctld-update
+++ b/lib/bkctld-update
@@ -13,10 +13,10 @@ if [ ! -n "${jail_name}" ]; then
 fi
 jail_path=$(jail_path "${jail_name}")
 
-test -d "${jail_path}" || error "${jail_name}: jail is missing."
+test -d "${jail_path}" || error "${jail_name}: jail not found"
 
 "${LIBDIR}/bkctld-is-on" "${jail_name}" && "${LIBDIR}/bkctld-stop" "${jail_name}"
 
 setup_jail_chroot "${jail_name}"
 
-notice "${jail_name}: jail has been updated."
+notice "Update jail \`${jail_name}' : OK"
diff --git a/lib/includes b/lib/includes
--- a/lib/includes
+++ b/lib/includes
@@ -23,43 +23,49 @@ CRITICAL="${CRITICAL:-48}"
 WARNING="${WARNING:-24}"
 DUC=$(command -v duc-nox || command -v duc)
 
+log_date() {
+    echo "[$(date +%Y-%m-%d %H:%M:%s)]"
+}
+process_name() {
+    basename $0
+}
 debug() {
     msg="${1:-$(cat /dev/stdin)}"
     if [ "${LOGLEVEL}" -ge 7 ]; then
-        echo "${msg}"
-        logger -t bkctld -p daemon.debug "${msg}"
+        echo "$(log_date) DEBUG $(process_name) ${msg}"
+        logger -t bkctld -p daemon.debug "$(process_name) ${msg}"
     fi
 }
 
 info() {
     msg="${1:-$(cat /dev/stdin)}"
     if [ "${LOGLEVEL}" -ge 6 ]; then
-        tty -s && echo "${msg}"
-        logger -t bkctld -p daemon.info "${msg}"
+        tty -s && echo "$(log_date) INFO  $(process_name)${msg}"
+        logger -t bkctld -p daemon.info "$(process_name) ${msg}"
     fi
 }
 
 notice() {
     msg="${1:-$(cat /dev/stdin)}"
-    tty -s && echo "${msg}"
-    [ "${LOGLEVEL}" -ge 5 ] && logger -t bkctld -p daemon.notice "${msg}"
+    tty -s && echo "$(log_date) NOTICE $(process_name) ${msg}"
+    [ "${LOGLEVEL}" -ge 5 ] && logger -t bkctld -p daemon.notice "$(process_name) ${msg}"
 }
 
 warning() {
     msg="${1:-$(cat /dev/stdin)}"
-    tty -s && echo "WARNING: ${msg}" >&2
+    tty -s && echo "$(log_date) WARNING $(process_name) ${msg}" >&2
     if [ "${LOGLEVEL}" -ge 4 ]; then
-        tty -s || echo "WARNING: ${msg}" >&2
-        logger -t bkctld -p daemon.warning "${msg}"
+        tty -s || echo "$(log_date) WARNING $(process_name) ${msg}" >&2
+        logger -t bkctld -p daemon.warning "$(process_name) ${msg}"
     fi
 }
 
 error() {
     msg="${1:-$(cat /dev/stdin)}"
-    tty -s && echo "ERROR: ${msg}" >&2
+    tty -s && echo "$(log_date) ERROR $(process_name) ${msg}" >&2
     if [ "${LOGLEVEL}" -ge 5 ]; then
-        tty -s || echo "ERROR: ${msg}" >&2
-        logger -t bkctld -p daemon.error "${msg}"
+        tty -s || echo "$(log_date) ERROR $(process_name) ${msg}" >&2
+        logger -t bkctld -p daemon.error "$(process_name) ${msg}"
     fi
     exit 1
 }
