error() function accepts an optional return code

diff --git a/lib/bkctld-is-on b/lib/bkctld-is-on
--- a/lib/bkctld-is-on
+++ b/lib/bkctld-is-on
@@ -14,7 +14,7 @@ if [ -z "${jail_name}" ]; then
 fi
 jail_path=$(jail_path "${jail_name}")
 
-test -d "${jail_path}" || error "${jail_name}: jail not found"
+test -d "${jail_path}" || error "${jail_name}: jail not found" 2
 
 jail_pid_file="${jail_path}/${SSHD_PID}"
 
diff --git a/lib/bkctld-key b/lib/bkctld-key
--- a/lib/bkctld-key
+++ b/lib/bkctld-key
@@ -15,7 +15,7 @@ if [ ! -n "${jail_name}" ]; then
 fi
 jail_path=$(jail_path "${jail_name}")
 
-test -d "${jail_path}" || error "${jail_name}: jail not found"
+test -d "${jail_path}" || error "${jail_name}: jail not found" 2
 
 if [ -z "${keyfile}" ]; then
     if [ -f "${jail_path}/${AUTHORIZED_KEYS}" ]; then
diff --git a/lib/bkctld-start b/lib/bkctld-start
--- a/lib/bkctld-start
+++ b/lib/bkctld-start
@@ -13,7 +13,7 @@ if [ -z "${jail_name}" ]; then
 fi
 jail_path=$(jail_path "${jail_name}")
 
-test -d "${jail_path}" || error "${jail_name}: jail not found"
+test -d "${jail_path}" || error "${jail_name}: jail not found" 2
 
 "${LIBDIR}/bkctld-is-on" "${jail_name}" && exit 0
 
