server: remove odd backticks

diff --git a/server/lib/bkctld-key b/server/lib/bkctld-key
--- a/server/lib/bkctld-key
+++ b/server/lib/bkctld-key
@@ -25,8 +25,8 @@ if [ -z "${keyfile}" ]; then
         cat "${jail_rootfs_path}/${AUTHORIZED_KEYS}"
     fi
 else
-    test -r "${keyfile}" || error "SSH key \`${keyfile}' for jail \`${jail_name}' is missing or is not readable."
+    test -r "${keyfile}" || error "SSH key '${keyfile}' for jail '${jail_name}' is missing or is not readable."
     cat "${keyfile}" > "${jail_rootfs_path}/${AUTHORIZED_KEYS}"
     chmod 600 "${jail_rootfs_path}/${AUTHORIZED_KEYS}"
-    notice "Update SSH key \`${keyfile}' for jail \`${jail_name}' : OK"
+    notice "Update SSH key '${keyfile}' for jail '${jail_name}' : OK"
 fi
diff --git a/server/lib/bkctld-rename b/server/lib/bkctld-rename
--- a/server/lib/bkctld-rename
+++ b/server/lib/bkctld-rename
@@ -16,7 +16,7 @@ if [ -z "${jail_name}" ] || [ -z "${new_jail_name}" ]; then
 fi
 
 jail_path=$(jail_path "${jail_name}")
-jail_rootfs_path=$(jail_rootfs_path "${jail_name}")
+#jail_rootfs_path=$(jail_rootfs_path "${jail_name}")
 incs_path=$(incs_path "${jail_name}")
 jail_config_dir=$(jail_config_dir "${jail_name}")
 legacy_config_file="${CONFDIR}/${jail_name}"
@@ -42,7 +42,7 @@ case "$?" in
     ;;
     *)
         unset jail_initial_status
-        error "Error evaluating jail \`${jail_name}' state. bkctld-is-on exited with \`$?'"
+        error "Error evaluating jail '${jail_name}' state. bkctld-is-on exited with '$?'"
     ;;
 esac
 
@@ -94,4 +94,4 @@ fi
 
 test "${jail_initial_status}" = "on" && "${LIBDIR}/bkctld-start" "${new_jail_name}"
 
-notice "Rename jail \`${jail_name}' to \`${new_jail_name}' : OK"
+notice "Rename jail '${jail_name}' to '${new_jail_name}' : OK"
diff --git a/server/lib/bkctld-start b/server/lib/bkctld-start
--- a/server/lib/bkctld-start
+++ b/server/lib/bkctld-start
@@ -21,8 +21,8 @@ test -d "${jail_path}" || error "${jail_name}: jail not found" 2
 test $(get_jail_version "${jail_name}") -ne ${CURRENT_JAIL_VERSION} && error "${jail_name}: jail needs to be updated to version ${CURRENT_JAIL_VERSION} (currently $(get_jail_version "${jail_name}")) - Use bkctld convert-v2 <jail>" 3
 
 # Start the jail
-notice "Starting jail \`${jail_name}'"
-systemctl start systemd-nspawn@${jail_name}  || error "Failed to start nspawn container for jail \`${jail_name}'"
+notice "Starting jail '${jail_name}'"
+systemctl start systemd-nspawn@"${jail_name}"  || error "Failed to start nspawn container for jail '${jail_name}'"
 
 if systemctl is-active --quiet systemd-nspawn@${jail_name}; then
     port=$("${LIBDIR}/bkctld-port" "${jail_name}")
@@ -47,16 +47,16 @@ if systemctl is-active --quiet systemd-nspawn@${jail_name}; then
     
 
     if [ "${success}" -eq 0 ]; then
-        notice "OK SSH : Started jail \`${jail_name}'"
+        notice "OK SSH : Started jail '${jail_name}'"
     else
-        if systemctl is-active --quiet systemd-nspawn@${jail_name}; then
-            error "WARNING SSH : Jail is running, but failed to get response from sshd for jail \`${jail_name}' within 3 seconds"
+        if systemctl is-active --quiet systemd-nspawn@"${jail_name}"; then
+            error "WARNING SSH : Jail is running, but failed to get response from sshd for jail '${jail_name}' within 3 seconds"
         else
-            error "Failed to to start \`${jail_name}' - Jail terminated. Check \`systemctl status systemd-nspawn@${jail_name}'"
+            error "Failed to to start '${jail_name}' - Jail terminated. Check 'systemctl status systemd-nspawn@${jail_name}'"
         fi
         
     fi
 
 else
-    error "Failed to to start \`${jail_name}' - Jail terminated. Check \`systemctl status systemd-nspawn@${jail_name}'"
+    error "Failed to to start '${jail_name}' - Jail terminated. Check 'systemctl status systemd-nspawn@${jail_name}'"
 fi
diff --git a/server/lib/bkctld-sync b/server/lib/bkctld-sync
--- a/server/lib/bkctld-sync
+++ b/server/lib/bkctld-sync
@@ -71,7 +71,7 @@ if "${LIBDIR}/bkctld-is-on" "${jail_name}"; then
             ssh "${NODE}" "${LIBDIR}/bkctld-start ${jail_name}" | debug
         ;;
         *)
-            error "Error evaluating jail \`${jail_name}' state. bkctld-is-on exited with \`$?'"
+            error "Error evaluating jail '${jail_name}' state. bkctld-is-on exited with '$?'"
         ;;
     esac
 else
