server: Move from chroot to systemd-nspawn
Big change :
-> systemd-nspawn usage instead of chroot
-> Folder directory structure changes

Before : /backup/jails/JAIL_NAME/ <- RootFS of chroot jail
Now :
-  /backup/jails/JAIL_NAME/rootfs <- Jail rootfs (ro)
-  /backup/jails/JAIL_NAME/var <- Jail /var (rw)
-  /backup/jails/JAIL_NAME/data <- Jail /data (rw)

New dependencies :
- systemd-nspawn (package systemd-container on Debian)
- check_ssh (package monitoring-plugins-basic on Debian

Still a Work In Progress.
As of now, it won't work on existing servers as the jail folders needs
to be converted to the new folder structure

diff --git a/server/lib/bkctld-ip b/server/lib/bkctld-ip
--- a/server/lib/bkctld-ip
+++ b/server/lib/bkctld-ip
@@ -13,11 +13,11 @@ ip="${2:-}"
 if [ ! -n "${jail_name}" ]; then
     show_help && exit 1
 fi
-jail_path=$(jail_path "${jail_name}")
+jail_rootfs_path=$(jail_rootfs_path "${jail_name}")
 
-test -d "${jail_path}" || error "${jail_name}: jail not found" 2
+test -d "${jail_rootfs_path}" || error "${jail_name}: jail rootfs not found" 2
 
-jail_sshd_config="${jail_path}/${SSHD_CONFIG}"
+jail_sshd_config="${jail_rootfs_path}/${SSHD_CONFIG}"
 
 if [ -z "${ip}" ]; then
     # parse IP addresses from AllowUsers directives in sshd config
diff --git a/server/lib/bkctld-start b/server/lib/bkctld-start
--- a/server/lib/bkctld-start
+++ b/server/lib/bkctld-start
@@ -17,27 +17,44 @@ test -d "${jail_path}" || error "${jail_name}: jail not found" 2
 
 "${LIBDIR}/bkctld-is-on" "${jail_name}" && exit 0
 
-# Prepare the chroot
-mount_jail_fs "${jail_name}"
 
-# Start SSH in the chroot
-chroot "${jail_path}" /usr/sbin/sshd -E /var/log/authlog || error "Failed to start SSH for jail \`${jail_name}'"
-pidfile="${jail_path}/${SSHD_PID}"
+# Start the jail
+notice "Starting jail \`${jail_name}\`"
+systemctl start systemd-nspawn@${jail_name}  || error "Failed to start nspawn container for jail \`${jail_name}'"
 
-# Wait for SSH to be up
-# shellcheck disable=SC2034
-for try in $(seq 1 10); do
-    if [ -f "${pidfile}" ]; then
-        pid=$(cat "${pidfile}")
-        break
+if systemctl is-active --quiet systemd-nspawn@${jail_name}; then
+    port=$("${LIBDIR}/bkctld-port" "${jail_name}")
+    success=1
+
+    for try in $(seq 1 10); do
+        # Is the jail still running?
+        if ! systemctl is-active --quiet systemd-nspawn@${jail_name}; then
+            printf 'x '
+            break
+        fi
+        
+        # Is SSH alive and responding ?
+        if /usr/lib/nagios/plugins/check_ssh  --port=${port} localhost 2>&1 >/dev/null; then
+            success=0
+            break
+        else
+            printf '.'
+            sleep 0.3
+        fi
+    done
+    
+
+    if [ "${success}" -eq 0 ]; then
+        notice "OK SSH : Started jail \`${jail_name}\`"
     else
-        pid=""
-        sleep 0.3
+        if systemctl is-active --quiet systemd-nspawn@${jail_name}; then
+            error "WARNING SSH : Jail is running, but failed to get response from sshd for jail \`${jail_name}\` within 3 seconds"
+        else
+            error "Failed to to start \`${jail_name}\` - Jail terminated. Check \`systemctl status systemd-nspawn@${jail_name}\`"
+        fi
+        
     fi
-done
 
-if [ -n "${pid}" ]; then
-    notice "Start jail \`${jail_name}' : OK [${pid}]"
 else
-    error "Failed to fetch SSH PID for jail \`${jail_name}' within 3 seconds"
+    error "Failed to to start \`${jail_name}\` - Jail terminated. Check \`systemctl status systemd-nspawn@${jail_name}\`"
 fi
